services:
  api:
    build:
      dockerfile: Dockerfile
    image: myproject-api
    container_name: myproject-api
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=myproject-db-host
      - DATABASE_POST=5432
      - DATABASE_USER=myproject
      - DATABASE_PASSWORD=myprojectpwd
      - DATABASE_NAME=myproject
      - JWT_SECRET=hello
      - API_PORT=8080
    ports:
      - '8080:8080'
    networks:
      - myproject-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: myproject-db-host
    ports:
      - '5432:5432'
    volumes:
      - myproject_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d myproject -U myproject" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - myproject-network
    environment:
      - POSTGRES_USER=myproject
      - POSTGRES_PASSWORD=myprojectpwd

volumes:
  myproject_db_data: {}

networks:
  myproject-network:
    driver: bridge
    external: true
