# Override Dockerfile to use vscode Node & Typescript image
# Bind volume to the current directory
services:
  api:
    build:
      dockerfile: .devcontainer/Dockerfile
    image: myproject-api-devcontainer
    volumes:
      - .:/api:cached
      - /api/node_modules
